#!/usr/bin/env python3
"""
fluid-tokens.py - GUILD-81 zoom-safe fluid token scale generator.

Generates Utopia-style clamp() CSS custom properties from four anchors:
min viewport, max viewport, min base size, max base size. Font tokens use a
rem + vw slope, never bare vw, so browser zoom still has a rem component.

  python3 scripts/fluid-tokens.py --out docs/guild/exports/fluid-tokens.css
  python3 scripts/fluid-tokens.py --selftest
"""
import argparse
import math
import sys

DEFAULT_MIN_VIEWPORT = 320
DEFAULT_MAX_VIEWPORT = 1280
DEFAULT_MIN_FONT_REM = 1.0
DEFAULT_MAX_FONT_REM = 1.25

TYPE_STEPS = {
    "type--2": (-2, 1.18),
    "type--1": (-1, 1.18),
    "type-0": (0, 1.18),
    "type-1": (1, 1.2),
    "type-2": (2, 1.22),
    "type-3": (3, 1.24),
    "type-4": (4, 1.26),
}

SPACE_STEPS = {
    "space-3xs": 0.25,
    "space-2xs": 0.5,
    "space-xs": 0.75,
    "space-s": 1.0,
    "space-m": 1.5,
    "space-l": 2.0,
    "space-xl": 3.0,
    "space-2xl": 4.0,
}


def round_css(value):
    return f"{value:.4f}".rstrip("0").rstrip(".")


def clamp(min_rem, max_rem, min_vw, max_vw):
    slope = (max_rem - min_rem) / (max_vw - min_vw) * 100
    intercept = min_rem - (slope * min_vw / 100)
    return f"clamp({round_css(min_rem)}rem, {round_css(intercept)}rem + {round_css(slope)}vw, {round_css(max_rem)}rem)"


def type_size(step, ratio, base_min, base_max):
    if step >= 0:
        return base_min * (ratio ** step), base_max * (ratio ** step)
    return base_min / (ratio ** abs(step)), base_max / (ratio ** abs(step))


def generate(min_viewport=DEFAULT_MIN_VIEWPORT, max_viewport=DEFAULT_MAX_VIEWPORT,
             min_font=DEFAULT_MIN_FONT_REM, max_font=DEFAULT_MAX_FONT_REM):
    lines = [
        "/* GUILD-81 fluid tokens: zoom-safe rem + vw clamp() scale. */",
        "/* Generated by scripts/fluid-tokens.py; source tokens.dtcg.json remains untouched. */",
        ":root {",
        f"  --guild-fluid-vw-min: {min_viewport}px;",
        f"  --guild-fluid-vw-max: {max_viewport}px;",
    ]
    for name, (step, ratio) in TYPE_STEPS.items():
        lo, hi = type_size(step, ratio, min_font, max_font)
        lines.append(f"  --guild-{name}: {clamp(lo, hi, min_viewport, max_viewport)};")
    for name, multiplier in SPACE_STEPS.items():
        lo = min_font * multiplier
        hi = max_font * multiplier
        lines.append(f"  --guild-{name}: {clamp(lo, hi, min_viewport, max_viewport)};")
    lines.extend([
        "  --guild-measure-readable: clamp(45ch, 62ch, 75ch);",
        "  --guild-container-inline-pad: clamp(var(--guild-space-s), 3vw, var(--guild-space-xl));",
        "}",
        "",
        ".guild-fluid-grid {",
        "  display: grid;",
        "  grid-template-columns: repeat(auto-fit, minmax(min(100%, 30ch), 1fr));",
        "  gap: var(--guild-space-m);",
        "}",
        "",
        ".guild-fluid-copy {",
        "  max-inline-size: var(--guild-measure-readable);",
        "  font-size: var(--guild-type-0);",
        "  line-height: 1.55;",
        "}",
    ])
    return "\n".join(lines) + "\n"


def selftest():
    css = generate()
    bare_vw_font = any(
        "font" in line and "vw" in line and "rem +" not in line
        for line in css.splitlines()
    )
    ok = (
        "--guild-type-0: clamp(1rem," in css
        and "--guild-space-m:" in css
        and "repeat(auto-fit, minmax(min(100%, 30ch), 1fr))" in css
        and not bare_vw_font
    )
    print("GUILD-81 fluid tokens - self-test")
    print(f"   clamp tokens: {css.count('clamp(')}")
    print(f"   bare vw font tokens: {bare_vw_font}")
    print(f"\n{'PASS' if ok else 'FAIL'} - zoom-safe fluid type, space, and intrinsic grid generated.")
    sys.exit(0 if ok else 1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ap.add_argument("--min-viewport", type=int, default=DEFAULT_MIN_VIEWPORT)
    ap.add_argument("--max-viewport", type=int, default=DEFAULT_MAX_VIEWPORT)
    ap.add_argument("--min-font-rem", type=float, default=DEFAULT_MIN_FONT_REM)
    ap.add_argument("--max-font-rem", type=float, default=DEFAULT_MAX_FONT_REM)
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        selftest()
    css = generate(a.min_viewport, a.max_viewport, a.min_font_rem, a.max_font_rem)
    if a.out:
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(css)
    else:
        print(css, end="")


if __name__ == "__main__":
    main()
